const multipleFormsConfig = [
  {
    title: 'Skills',
    inputs: [
      {
        title: 'skill',
        id: 'technical-skill',
        type: 'text',
        label: 'Technical Skill',
        required: true,
        placeholder: 'Software Engineer',
        maxLength: 20,
        minLength: 3,
        pattern: null,
        titleAttribute: 'Technical Skill: Enter a skill (3–20 characters)',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'skillsDescription',
        id: 'skills-description',
        type: 'textarea',
        label: 'Description of your skills',
        required: false,
        placeholder: null,
        maxLength: 250,
        minLength: 3,
        pattern: null,
        titleAttribute:
          'Description of your skills: Optional description (3–250 characters)',
        step: null,
        max: null,
        min: null,
      },
    ],
    key: 'skills-form-group',
  },
  {
    title: 'Education',
    inputs: [
      {
        title: 'university',
        id: 'university-name',
        type: 'text',
        label: 'University',
        placeholder: 'Enter university or school',
        required: true,
        maxLength: 20,
        minLength: 3,
        pattern: null,
        titleAttribute:
          'University: Enter university or school name (3–20 characters)',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'degree',
        id: 'degree-title',
        type: 'text',
        label: 'Degree',
        placeholder: 'Enter your Degree title',
        required: true,
        maxLength: 20,
        minLength: 3,
        pattern: null,
        titleAttribute: 'Degree: Enter your degree title (3–20 characters)',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'educationStartDate',
        id: 'education-start-date',
        type: 'date',
        label: 'Start Date',
        placeholder: null,
        required: false,
        maxLength: null,
        minLength: null,
        pattern: null,
        titleAttribute: 'Start Date: Pick the start date of your education',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'educationEndDate',
        id: 'education-end-date',
        type: 'date',
        label: 'End Date',
        placeholder: null,
        required: false,
        maxLength: null,
        minLength: null,
        pattern: null,
        titleAttribute: 'End Date: Pick the end date of your education',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'gpa',
        id: 'gpa',
        type: 'number',
        label: 'Your GPA',
        placeholder: 'e.g. 3.9',
        required: false,
        pattern: '/^(?:[0-4](?:.d{1,2})?|5(?:.0{1,2})?)$/',
        titleAttribute:
          'Your GPA: Enter GPA between 0.00 and 5.00 (up to 2 decimal places)',
        step: 0.01,
        max: 5,
        min: 0,
      },
    ],
    key: 'education-form-group',
  },
  {
    title: 'Experience',
    inputs: [
      {
        title: 'company',
        id: 'company-name',
        type: 'text',
        label: 'Company Name',
        placeholder: 'Enter Company Name',
        required: true,
        maxLength: 20,
        minLength: 3,
        pattern: null,
        titleAttribute:
          'Company Name: Enter the name of the company (3–20 characters)',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'jobTitle',
        id: 'job-title',
        type: 'text',
        label: 'Job Title',
        placeholder: 'Enter Job Title',
        required: true,
        maxLength: 20,
        minLength: 3,
        pattern: null,
        titleAttribute: 'Job Title: Enter your job title (3–20 characters)',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'jobStartDate',
        id: 'job-start-date',
        type: 'date',
        label: 'Start Date',
        placeholder: null,
        required: false,
        maxLength: null,
        minLength: null,
        pattern: null,
        titleAttribute: 'Start Date: Pick the start date of your job',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'jobEndDate',
        id: 'job-end-date',
        type: 'date',
        label: 'End Date',
        placeholder: null,
        required: false,
        maxLength: null,
        minLength: null,
        pattern: null,
        titleAttribute: 'End Date: Pick the end date of your job',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'jobDescription',
        id: 'job-description',
        type: 'textarea',
        label: 'Summary about your Job',
        required: false,
        placeholder: null,
        maxLength: 250,
        minLength: 3,
        pattern: null,
        titleAttribute:
          'Summary about your Job: Optional summary (3–250 characters)',
        step: null,
        max: null,
        min: null,
      },
    ],
    key: 'experience-form-group',
  },
];

export default multipleFormsConfig;
