const singleFormsConfig = [
  {
    title: 'General',
    inputs: [
      {
        title: 'fullName',
        id: 'full-name',
        type: 'text',
        label: 'Full Name',
        required: true,
        placeholder: 'e.g. Emrah Isovic',
        maxLength: 25,
        minLength: 3,
        pattern: null,
        titleAttribute:
          'Full Name: Enter your full name (3–25 characters, first letters uppercase)',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'description',
        id: 'personal-description',
        type: 'textarea',
        label: 'Summary about yourself',
        required: true,
        placeholder: null,
        maxLength: 250,
        minLength: 1,
        pattern: null,
        titleAttribute:
          'Summary about yourself: Optional description (1–250 characters)',
        step: null,
        max: null,
        min: null,
      },
    ],
    key: 'general-form-group',
  },
  {
    title: 'Contact',
    inputs: [
      {
        title: 'emailAddress',
        id: 'email',
        type: 'email',
        label: 'Email',
        required: true,
        placeholder: 'e.g.  emrahisovic20@gmail.com',
        maxLength: 40,
        minLength: 2,
        pattern: '^[a-z0-9._%+\\-]+@[a-z0-9.\\-]+\\.[a-z]{2,}$',
        titleAttribute:
          'Email: Enter a valid email address (e.g. emrahisovic20@gmail.com)',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'phoneNumber',
        id: 'phone-number',
        type: 'tel',
        label: 'Phone Number',
        required: false,
        placeholder: 'e.g.  +123 456 7890',
        maxLength: 20,
        minLength: 7,
        pattern: null,
        titleAttribute:
          'Phone Number: Enter a valid phone number (7–20 digits, optional +, (), - or spaces)',
        step: null,
        max: null,
        min: null,
      },
      {
        title: 'address',
        id: 'location-address',
        type: 'text',
        label: 'Address',
        required: false,
        placeholder: 'e.g.  Sarajevo, B&H',
        maxLength: 40,
        minLength: 2,
        pattern: null,
        titleAttribute:
          'Address: Optional – Enter your address (2–40 characters)',
        step: null,
        max: null,
        min: null,
      },
    ],
    key: 'contact-form-group',
  },
];

export default singleFormsConfig;
